name: viernes_mobile
description: A clean Flutter project for Viernes Mobile app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # UI & Theming
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.0
  date_picker_plus: ^3.0.2

  # Forms
  phone_form_field: ^9.0.0

  # Charts and Data Visualization
  fl_chart: ^0.68.0

  # Navigation
  go_router: ^12.1.3

  # Authentication
  google_sign_in: ^6.2.1
  local_auth: ^2.1.8

  # HTTP Client
  dio: ^5.4.3+1

  # Cache and Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  file_picker: ^8.1.3

  # Chat & Real-time
  web_socket_channel: ^2.4.0

  # Local Notifications
  flutter_local_notifications: ^19.0.0

  # Pull to refresh
  pull_to_refresh: ^2.0.0

  # Animations & Interactions
  lottie: ^3.1.0
  shimmer: ^3.0.0

  # Utilities
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  package_info_plus: ^9.0.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/auth/logo.png
    - assets/images/auth/powered-by-2.png
